image: node:8.4.0

pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install hexo-cli -g
  - npm install
  - export HEXO_ALGOLIA_INDEXING_KEY=c722ddd1ba7f457a9bc653c47ebd6284
  - hexo algolia
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
