language: node_js
node_js:
- 8.11.4

before_install:
- openssl aes-256-cbc -K $encrypted_befb9cbc6467_key -iv $encrypted_befb9cbc6467_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- cp .travis/config ~/.ssh/config
- chmod 600 ~/.ssh/id_rsa

install:
- npm install
- npm i -g hexo-cli

script:
- hexo g
- hexo algolia
- hexo d

after_script:
- cd ./public
- tar -czf blogSource.tar.gz *
- scp blogSource.tar.gz blog@45.32.44.113:~/
- ssh blog@45.32.44.113 'rm -rf blogSource'
- ssh blog@45.32.44.113 'mkdir -p blogSource && tar -xzvf blogSource.tar.gz -C blogSource'

deploy:
  provider: pages
  local_dir: public/
  repo: BroKun/BroKun.github.io
  target_branch: master
  email: brokun0128@gmail.com
  name: BroKun
  skip_cleanup: true
  github_token: "${github_token}"
  on:
    branch: master

branches:
  only:
  - master

