language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "BroKun"
  - git config user.email "brokun0128@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${github_token}@${github_ref}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - github_ref: github.com/BroKun/BroKun.github.io.git
