language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_3550d7f81954_key -iv $encrypted_3550d7f81954_iv
  -in .travis/id_rsa.enc -out  ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 45.32.44.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "BroKun"
- git config user.email "brokun0128@gmail.com"
- git add .
- git commit -m "Update docs"
- git push --force --quiet "https://${github_token}@${github_ref}" master:master
- tar -czf blogSource.tar.gz *
- scp blogSource.tar.gz blog@45.32.44.113:~/
- ssh blog@45.32.44.113 'rm -rf blogSource'
- ssh blog@45.32.44.113 'mkdir -p blogSource && tar -xzvf blogSource.tar.gz
  blogSource'
branches:
  only:
  - master
env:
  global:
  - github_ref: github.com/BroKun/BroKun.github.io.git
