language: node_js
node_js:
- 8.1.3

before_install:
- openssl aes-256-cbc -K $encrypted_befb9cbc6467_key -iv $encrypted_befb9cbc6467_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d # 生产机登录密钥
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 101.200.36.181\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config # 跳过严格检查
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- git config --global user.name "BroKun"
- git config --global user.email "wangyukun1234@hotmail.com"

install:
- npm install
- npm i -g hexo-cli

script:
- hexo g
- hexo algolia
- hexo d

deploy:
  provider: pages
  local_dir: public/
  repo: BroKun/BroKun.github.io
  target_branch: master
  email: brokun0128@gmail.com
  name: BroKun
  skip_cleanup: true
  github_token: "${github_token}"
  on:
    branch: master

branches:
  only:
  - master

