language: node_js
node_js: stable
install:
- npm install
script:
- hexo g
- hexo algolia
deploy:
  provider: pages
  local_dir: public/
  repo: BroKun/BroKun.github.io
  target_branch: master
  email: brokun0128@gmail.com
  name: BroKun
  skip_cleanup: true
  github_token: ${github_token} # Set in travis-ci.org dashboard
  on:
    branch: master
branches:
  only:
  - master
